---

- hosts: all
  become: true
  tasks:

  - name: Enabling UFW, allowing all traffic
    community.general.ufw:
      state: enabled
      policy: allow

  - name: Set logging
    community.general.ufw:
      logging: 'on'

  - community.general.ufw:
      rule: reject
      port: auth
      log: yes

  - name: Denying access to port 35
    community.general.ufw:
      rule: deny
      port: '35'

  - name: Allowing all access to port 53
    community.general.ufw:
      rule: allow
      port: '53'
      proto: tcp

  - name: Allow port range 60000-61000
    community.general.ufw:
      rule: allow
      port: 60000:61000
      proto: tcp
